### ISSUE TITLE
Bug: Mobile nav connect button is too big

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1036]
### Describe the bug

This PR https://github.com/open-sauced/insights/pull/1029 introduce a bug with the connect button.

<img width="402" alt="Screen Shot 2023-03-21 at 8 25 35 PM" src="https://user-images.githubusercontent.com/5713670/226794445-3334a2b1-089c-442c-ba5a-0c30d51d012e.png">

cc @nworiekingslee 

### Steps to reproduce

We need to fix the logged out view on mobile. 

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nworiekingslee** [comment]
Is the button wrapping the problem?

**Comment by nworiekingslee** [comment]
Here are my suggestions to fix the problem,
- I could truncate it with ellipses for when the button can't find room to grow
- I could just re-word the CTA to something shorter. Like "Login"

What do you think @bdougie

**Comment by parmishh** [comment]
@bdougie I would like to work on this issue you can assign me

**Comment by nworiekingslee** [comment]
> None of these sound like solutions but work around to not address the issue.
> 
> A better solution preventing wrapping and reorder elements for mobile only.

Okay. I understand. 

You can assign me to the issue

**Comment by nworiekingslee** [comment]
Apologies for the delay. I will fix this today. Happy New Week BTW

**Comment by 0-vortex** [comment]
Depending on the platform, just making the button smaller is not enough. Considering how horrible it looks on mobile, a quick fix is good enough 😅 

Some requirements to make the header perfect:
1. the button is not responsive, it is hacked from desktop to mobile with different classes -> needs mobile classes attached as defaults and then manipulated for higher screens with sm/md/lg
2. there is a wrapper around the button defining the spacing, however, the height is not fixed to the logo or other flex items on the right -> this needs removed or adjusted if adjusted it needs to encapsulate the left flex items (dry)
3. the left navigation is not even, with 49 pixels total height, this needs to be addressed on a line height level to match the buttons we place on the right, otherwise, there will be pixel discrepancies between screens or platforms (they can be seen now even on a desktop)
