### ISSUE TITLE
A Thinner and Theme matched Scrollbar would be Great.

### ISSUE THREAD

**Issue by parmishh** [open-sauced/insights#1054]
### Type of feature

🍕 Feature

### Current behavior

The Scrollbar Doesn't matches the theme.
<img width="959" alt="Capture2" src="https://user-images.githubusercontent.com/91942072/228014944-1a1dc7b9-5419-4343-b66b-29124e619954.PNG">

@bdougie what are your views?
I can implement it easily if this feature is wanted

### Suggested solution

A Thinner and Theme matched Scrollbar would be Great.
I have experimented 
Something like this:

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/91942072/228014633-90bc4644-5865-4f60-99c9-6b6de0c9b786.PNG">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by parmishh** [comment]
@shamimbinnur 👍

**Comment by TAKANOME-DEV** [comment]
+1 rounded edge and maybe lighter gray

**Comment by 0-vortex** [comment]
Super hard pushback on this, some friendly resources to give you a hint:
- https://css-tricks.com/the-current-state-of-styling-scrollbars-in-css/
- https://css-tricks.com/almanac/properties/s/scrollbar/

Beyond the inability to find a common denominator, extra concerned about mobile usage, where have to mention the scrollbars are just fine. The psychological attention vector should also be on the left/top of the page, not the right/bottom 😅

**Comment by parmishh** [comment]
@bdougie @shamimbinnur @TAKANOME-DEV 
Any Suggestions on this implemented Scrollbar I made it little thinner, Gray and With Rounded edges.

https://user-images.githubusercontent.com/91942072/228260351-24766ff9-c1bc-44ea-bb92-4361962aa3cf.mp4

**Comment by NsdHSO** [comment]
@parmishh  Can you give us a screen recording in mobile dev

**Comment by parmishh** [comment]
@NsdHSO currently I don't see a scrollbar in mobile view in website is it required?

**Comment by 0-vortex** [comment]
> @NsdHSO currently I don't see a scrollbar in mobile view in website is it required?

There is a scrollbar on mobile, however, due to how different platforms work, they might be hidden until the page scrolls past the viewport. The problem with customizing scrollbars is visual/design cohesion across platforms. If users want to improve their experience on let's say, a desktop, they have options like plugins: https://chrome.google.com/webstore/detail/custom-scrollbars/ddbipglapfjojhfapmpmofnaoellkggc?hl=en

**Comment by parmishh** [comment]
@0-vortex yes I am aware about the extensions available. I also have a extension on chrome store which does the same.
So, Shall we work on modifying  the Scrollbar for mobiles?

**Comment by bdougie** [comment]
I think this should be scoped into an internal design review meeting. I also don't think the rounded scrollbar looks good at all. Rather than spend a cycle on a feature that is frankly not needed, I am going to close this issue and suggest @parmishh grab an open issue in our [Papercuts](https://github.com/open-sauced/insights/milestone/13) milestone instead.
