### ISSUE TITLE
Bug: redirect rules make viewing individual highlights difficult

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/insights#1145]
### Describe the bug

Unable to visit individual highlights, like https://insights.opensauced.pizza/feed/120 due to redirect issues

### Steps to reproduce

https://user-images.githubusercontent.com/237133/236337610-37798b2e-a735-4865-ba8e-8795d8bbdd56.mov

### Affected services

insights.opensauced.pizza

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Isn't it easier to add a page for a single highlight? :thinking:

**Comment by 0-vortex** [comment]
> Isn't it easier to add a page for a single highlight? 🤔

Well, search engines ... It's easier too 😅

**Comment by a0m0rajab** [comment]
This was fixed, Not sure where or how this was fixed (I prefer to link it to it's related PR, though) for archive purposes. 

Here is a screen record of today's behavior.  

https://github.com/open-sauced/insights/assets/18273833/bb4c94a3-29e8-45c5-a966-7b884879f9e5

Closing the issue due to it's being solved. 

Related codes:
https://github.com/open-sauced/insights/blob/932568ffe78b810b68fa0f053e62c87f7f9ceb9d/middleware.ts#L1-L29

Related PRs: 
https://github.com/open-sauced/insights/pull/1301
https://github.com/open-sauced/insights/pull/1208
https://github.com/open-sauced/insights/pull/1184
