### ISSUE TITLE
Feature: Odd design for large screens

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1231]
### Type of feature

🎨 Style

### Current behavior

When you are on large screen, the add to insights button and the table collabse.
![image](https://github.com/open-sauced/insights/assets/18273833/f25978e5-5f15-4248-b293-b8f5b4c5d1e7)
a 

### Suggested solution

It would be great to keep the button visible 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by NsdHSO** [comment]
@a0m0rajab I think the button is not visible because the table on `lg` screen of the container becomes a bad resolution 
I think this issue can have a `good-first-issue`https://github.com/open-sauced/insights/blob/ede678b5624ec3a2406789e0a8dfec0880fd8080/components/organisms/Repositories/repositories.tsx#L97

**Comment by RitaDee** [comment]
Can I attend to this issue?

**Comment by RitaDee** [comment]
.take
