### ISSUE TITLE
bug: Python is not in the list

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1273]
I can't upload an image but the filters on the dashboard does include Python

**Comment by bdougie** [comment]
Turns out this is just a problem on mobile. The list is abbreviated.

## mobile

## desktop
<img width="261" alt="Untitled" src="https://github.com/open-sauced/insights/assets/5713670/a6a26797-8124-4cc9-aeee-4b2387ceb112">

**Comment by OgDev-01** [comment]
Hey @bdougie Is the option list on mobile not scrollable?

**Comment by bdougie** [comment]
> Hey @bdougie Is the option list on mobile not scrollable?

Not on my phone.

**Comment by takanome-dev** [comment]
Radix ui has a [scroll area](https://www.radix-ui.com/docs/primitives/components/scroll-area) component that we can use and there is a nice integration with tailwind that we can just take [here](https://ui.shadcn.com/docs/components/scroll-area)

**Comment by babblebey** [comment]
Hey @takanome-dev, I think we should look to take advantage of the Scroll Sub-Components on the Radix UI's `Select` Primitive.

These are:

- [ScrollUpButton](https://www.radix-ui.com/docs/primitives/components/select#scrollupbutton)
- [ScrollDownButton ](https://www.radix-ui.com/docs/primitives/components/select#scrolldownbutton)

These components adds scroll buttons on-demand to the top/bottom of the `Select.Content` component in affordance to show the overflown content.

It also has support for scroll on touch devices, I think it will fit well since the component are already local i.e. sub-component to the `@radix-ui/react-select` Primitive implemented in our `Select` component.

What do you think??

**Comment by takanome-dev** [comment]
Oh great, I think we can use that one. Wanna give it a try?

**Comment by babblebey** [comment]
Great, I'm happy to .take this 😉

Thank you || Danke || O ṣeun
