### ISSUE TITLE
Feature: Insights Page Visibility Action placement 

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1298]
### Type of feature

🍕 Feature

### Current behavior

90% of the total times I have created insights pages, I have hardly scrolled to the bottom of the page to make my page public 
<img width="1126" alt="image" src="https://github.com/open-sauced/insights/assets/62995161/79b0dc6b-d2ff-43ad-a9fa-f6e458da4ab0">

### Reasons are:
- I mostly don't remember there being an action to trigger between public and private pages
- The action is hidden in an area that is not visible to any user that is creating a new insights page

Sometimes I end up creating a private page and having to return back to make it public after the creation

### Suggested solution

My suggestion is we move the page visibility toggle action into the below view area
<img width="1426" alt="insights" src="https://github.com/open-sauced/insights/assets/62995161/808e077e-8303-4048-bbde-a8c61fd5b902">

This way users get to see this action while selecting and creating new insights without having to scroll
cc: @bdougie and @brandonroberts Thoughts on this?

### Additional context

We might also want to consider having a short description of what making a page public or private means to your insights 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
Great stuff @OgDev-01 

In addition to this though, and with mobile usage experience in mind, It's imperative to place all form fields above/before the form action/submit button. 

Repositioning the "Page Visibility" to sit below the "Added Repository" box, will send it even further down on mobile, hence transferring our concerns to mobile, even though it wasn't a worry with the current set-up.

![IMG_20230626_083325.jpg](https://github.com/open-sauced/insights/assets/25631971/33be78db-e4c0-4043-bd92-f5cb3472b1ba)

For this reason, I would suggest that the "Page Visibility" is positioned above the "Added Repository" box due to the fact that it's where the form action/submit button resides.

That way it persists its position above the "Added Repository" box on mobile.

What do you think??
