### ISSUE TITLE
Feature: keep the list of notifications for some time after they have been viewed

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/insights#1444]
### Type of feature

🍕 Feature

### Current behavior

When checking my notifications, I saw some people follow me and I wanted to follow them back. But, after clicking on one notif and following that user, the list of notifications is gone and I don't see a way to view my followers (without querying the API)

https://github.com/open-sauced/insights/assets/79809121/46558a85-ad76-4551-bd36-14fc0cb0a287

### Suggested solution

I didn't find the pr where this was done (cc @OgDev-01) but how about keeping the notifs for some days after they have been viewed. 

Is there a feature (planned) where we can see the list of followers? cc @bdougie

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
@brandonroberts I saw that the notifications are marked as read when they are retrieved in the API. Can we keep them for like a week before marking them as read? or mark one as read when it's clicked?

**Comment by bdougie** [comment]
It might be worth marking them read but still listing them. 

I see a list of notifications I can't act on, because once I click they are gone. 

<img width="443" alt="Screen Shot 2023-07-31 at 9 44 16 PM" src="https://github.com/open-sauced/insights/assets/5713670/f03824ed-57f6-4729-a0ac-f2844fc22306">

Next time I check I see this 

<img width="424" alt="Screen Shot 2023-07-31 at 9 44 27 PM" src="https://github.com/open-sauced/insights/assets/5713670/54c9a03d-da92-4a2f-9cd6-300f43329fea">

Not a great experience and encourages me to ignore notifications. 

## suggestion

We can create a notification tab for the user view a paginated list similar to https://dev.to/notifications.

i.e. https://insights.opensauced.pizza/user/bdougie/notifications - it doesn't need a lot of thought in design just a simple page listing notifications for now.

**Comment by takanome-dev** [comment]
Great, this also needs API updates :pizza:

**Comment by bdougie** [comment]
> Great, this also needs API updates 🍕

How so? Is this not enough? https://api.opensauced.pizza/v1/user/notifications?page=1&limit=10&range=30

**Comment by bdougie** [comment]
Nevermind. I see the mark as read is built into the API and not the UI.

**Comment by takanome-dev** [comment]
Q. Should the new notifications page be SSR or CSR?

**Comment by OgDev-01** [comment]
> Q. Should the new notifications page be SSR or CSR?

We should go with CSR as the notifications are lightweight. SSR is mostly recommended for pages with heavy data fetching and SEO.
