### ISSUE TITLE
Bug: Empty Current Interest return 404 

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/insights#1454]
### Describe the bug

Empty current interest throws 404 when a user clicks on the icon-like shape below it:

![44E38AB3-0FE6-4C9C-B1B9-8FD217938FCF](https://github.com/open-sauced/insights/assets/106407013/a2e82bb8-adf4-4014-acb4-c6d596409d50)

### Steps to reproduce

Sign up with a user that has no interest.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Hey @RitaDee, I tried reproducing this but it all seems ok from my end.
![Screenshot 2023-07-31 at 19 37 11](https://github.com/open-sauced/insights/assets/62995161/5b3ea088-8d2c-4dbb-8252-0f649b69fae2)

This might be some issue related to a slow network connection and the interest is still loading when you clicked on the shape. By default, users have javascript as an interest even without selecting any.

**Comment by OgDev-01** [comment]
You can try to reproduce again to confirm if the issue still persists. If yes then we can do a little dig-in to debug 👍

**Comment by RitaDee** [comment]
Here is what it looks like on my end:

![7ED41921-E344-434E-8ED9-A57C8D97692C](https://github.com/open-sauced/insights/assets/106407013/ff305043-1acb-444f-b9c4-3259eaae9bff)

Can you send the link you are using to check?

**Comment by a0m0rajab** [comment]
This issue has been opened before, but I could not find it.

**Comment by takanome-dev** [comment]
So basically, when you have no interests, the API returns an empty string and then we try to split it by a comma to return an array of interests. That's why this is happening.
```js
const interests = "";
const arrayOfInterests = interests.split(",");
// return [""] the actual issue
```
Can be fixed by filtering falsy values: `interests?.split(",").filter(Boolean)`
https://github.com/open-sauced/insights/blob/31a9a6abda62c84475266e602ad95a5b62ab5fab/components/molecules/ContributorProfileInfo/contributor-profile-info.tsx#L44
@RitaDee feel free to take it

**Comment by RitaDee** [comment]
I will work on this one.

.take
