### ISSUE TITLE
Bug:  error on updating insight page

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1502]
### Describe the bug

When you try to update insight it page it's just kicking me off the page. 

https://github.com/open-sauced/insights/assets/18273833/ebd1cf3b-26be-4059-90c2-15f8fa2b15da

I am getting CORS policy issue. 

### Steps to reproduce

1. go to insigts page: https://insights.opensauced.pizza/hub/insights
2. try to update any page
3. you will not be able to update.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
@a0m0rajab that's weird because it's working fine on my end

https://github.com/open-sauced/insights/assets/79809121/db44b339-d969-49d4-abe7-a0762c0df815

**Comment by a0m0rajab** [comment]
That's pretty weird, seems similar to https://github.com/open-sauced/insights/issues/1309
I think I might need to check chrome settings.

**Comment by a0m0rajab** [comment]
Tried brave and it worked...

**Comment by jpmcb** [comment]
Hmmm interesting: works fine for me on FireFox. The only console errors I see are from PostHog but nothing throwing 502 or 404 from the server side.

It may be interesting to get a dump of your chrome settings since you've run into strange CORs errors before:
- What version of chrome you're on?
- Any custom settings you've added?
- Any / all plugins you have installed?

**Comment by a0m0rajab** [comment]
Thanks for this answer! The plugin's question showed me the issue, I had allow cors function, which was causing this issue! Disabling it solved the issue. 
![image](https://github.com/open-sauced/insights/assets/18273833/228810ff-3d42-41c8-950c-36bc76afb456)
I did not have any custom settings.
