### ISSUE TITLE
Bug: Avatar is either not shown or is not the user

### ISSUE THREAD

**Issue by adiati98** [open-sauced/insights#1529]
### Describe the bug

I opened the notification and the avatars of the same user are either empty or not the user.

#### Screenshot
 
![avatar](https://github.com/open-sauced/insights/assets/45172775/c9d4f331-edbf-4738-9e36-c42aa4daaf09)

(I'm sure the first avatar is not @BekahHW 😁) 

### Steps to reproduce

1. Click the notification icon.
2. See the avatars of the users.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
In your case, I think what's happening is that Bekah is reacting to different highlights (notice the different numbers) you've posted but since the profile pictures aren't being loaded, it looks odd.

I noticed something similar where people's profile pictures aren't being loaded even though I know they have images (like bdougie, martin, etc)

<img width="432" alt="Screenshot 2023-08-08 at 8 10 59 PM" src="https://github.com/open-sauced/insights/assets/23109390/821e9e53-2ea9-4cd5-8d08-6a7444a780c1">

**Comment by bdougie** [comment]
This error may due to the notification meta_id being used here. We have access to the user id, but we cache users based on usernames.

We will probably need an API update to include username. 

https://github.com/open-sauced/insights/pull/1478/files#diff-2524a786a0bcb5deadfbb244b5d5ef18304b923e055b9f64c1dd9fd0c695a592R158

We will also don't need to add the meta_id to the message. Weird seeing `239 BekahHW did a thing`

**Comment by takanome-dev** [comment]
> We will probably need an API update to include username.
> 
Agree
> We will also don't need to add the meta_id to the message. Weird seeing `239 BekahHW did a thing`

Indeed, but we need to include the highlight_id though. Should we keep meta_id which can be the username or highlight_id and add a username property?

cc @brandonroberts

**Comment by bdougie** [comment]
In my example above 239 is the highlight ID. The user does not need to see that in the text, to be clear keeping that in the response from the API is expected.

There is no value with having 239 in my notification. That needs to be removed in the UI.

This should be a straight forward API update. Could you open the issue @takanome-dev so we discuss there.

**Comment by brandonroberts** [comment]
> In my example above 239 is the highlight ID. The user does not need to see that in the text, to be clear keeping that in the response from the API is expected.
> 
> There is no value with having 239 in my notification. That needs to be removed in the UI.
> 
> This should be a straight forward API update. Could you open the issue @takanome-dev so we discuss there.

Yes, we can add "from" user information to each notification in the API. 

Here is an example
https://github.com/open-sauced/api/blob/beta/src/user/user.entity.ts#L522
https://github.com/open-sauced/api/blob/beta/src/user/entities/user-collaboration.entity.ts#L53

The `meta_id` field should be used along with the `type` to build the URL of where it should link to, which is what we had in the UI before with the notification bell.

**Comment by takanome-dev** [comment]
I realized that this was a silly mistake I made since I didn't have highlight reaction notification :sweat:. Submitted a fix for it. 

Should I keep working on the pr in the API to include the user information, @brandonroberts @bdougie?
