### ISSUE TITLE
Bug: Profile header is squashed due to new margins

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1543]
### Describe the bug

<img width="1728" alt="Screen Shot 2023-08-10 at 11 15 54 PM" src="https://github.com/open-sauced/insights/assets/5713670/c1022c59-a57e-43e5-964f-1c9dcb60b9ec">

### Steps to reproduce

View a profile full screen on the laptop.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

This fix needs to not break any other page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
The pr https://github.com/open-sauced/insights/pull/1490 broke the profile page because the feed page is using the layout wrapper of the profile page. So when Rita fixed the feed page responsiveness, it actually broke the profile page.

We should probably have layout wrapper for the feed.

Will try to find out more about the card page

**Comment by a0m0rajab** [comment]
Just a note here to prevent such behaviour in the future and be sure that we will not have any issues we might need to have snapshot tests. I opened an issue for that. 

Thanks takanome for your comment, it's really useful.

**Comment by babblebey** [comment]
The PR [fix: enhance feed layout responsiveness #1538](https://github.com/open-sauced/insights/pull/1538) will fix the issue.
