### ISSUE TITLE
Bug: some avatars cannot be processed

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/insights#733]
### Describe the bug

Spike in logged in users rate limits us on big resources, and we are loading avatars at 4k resolution for some unknown reason.

<img width="376" alt="Screenshot 2022-12-23 at 22 07 29" src="https://user-images.githubusercontent.com/237133/209401424-c0dfa4d7-8f1a-471f-93f6-995cf85634d0.png">

The fix should be changing line 50 in `auth-section.tsx` from ```<Avatar alt="User Avatar" avatarURL={user ? user.user_metadata.avatar_url : userAvatar} size={"base"} hasBorder={true} />``` to our previous default url of `https://avatars.githubusercontent.com/u/${user.id}?s=40&v=4` - the same as GitHub's displayed profile. This image does not require Cloudinary caching and it should be avoided

### Steps to reproduce

1. Sign in
2. Be unlucky
3. Never get to see your avatar

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
More context or links to commits would be helpful here @0-vortex  

## My proposed fix
We should not use username.id, but instead fetch based on `user.login`. The contributor calendar already stores 80k users based on the `username.png` pattern. 

Trying this now to see if this is valid.

https://github.com/open-sauced/insights/blob/9076e914cf60ffff351acd1968446cc85ab087a9/components/molecules/AuthSection/auth-section.tsx#L37

## Design System 
Pointing out that this needs to be fixed in the design system. Weird that event the unsplash image is not used as a fallback. 

https://design-insights.netlify.app/?path=/story/design-system-atoms-avatar--default

**Comment by 0-vortex** [comment]
> More context or links to commits would be helpful here @0-vortex
> 
> ## My proposed fix
> We should not use username.id, but instead fetch based on `user.login`. The contributor calendar already stores 80k users based on the `username.png` pattern.
> 
> Trying this now to see if this is valid.
> 
> https://github.com/open-sauced/insights/blob/9076e914cf60ffff351acd1968446cc85ab087a9/components/molecules/AuthSection/auth-section.tsx#L37
> 
> ## Design System
> Pointing out that this needs to be fixed in the design system. Weird that event the unsplash image is not used as a fallback.
> 
> https://design-insights.netlify.app/?path=/story/design-system-atoms-avatar--default

Sorry I missed mentioning that this should not pass through Cloudinary at all, since it is the same image and size as the GitHub avatar login in the GitHub platform - we would not have to process this image since it is cached in the login process. That can be done by either changing the size to a number, like `40` pixels, or switching to the default avatar.

**Comment by bdougie** [comment]
FYI, @SunGoldTech looks like this were introduced with this PR. https://github.com/open-sauced/insights/pull/691

Perhaps we missed focusing on the profile avatars and overlooking the login.
