### ISSUE TITLE
Bug: Search not working to search github repositories 

### ISSUE THREAD

**Issue by SimranjitKaurMaan** [open-sauced/insights#786]
### Describe the bug

On trying to search for a particular repo from the list of repos listed below, the searched repo is not filtered out.
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/9392954/212704232-1ca72cb2-f9b3-4d42-8c0c-b3cecff3c35f.png">

### Steps to reproduce

1. https://insights.opensauced.pizza/go/repositories
2. Go to repositories tab, and click to search a repository from the list below.
3. The repository is not highlighted or shown up
<img width="1700" alt="image" src="https://user-images.githubusercontent.com/9392954/212704966-64498a08-6c52-4174-87bd-8048a84ab1b9.png">

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Hey @SimranjitKaurMaan, this is not actually a bug but rather a completely missing feature. The way we can make it work is use the GitHub GraphQL or REST api to search for the repo, then once the user clicks on it, it would filter the search results.

The API will not support full text / name search, we will need higher availability (elastic) systems for that purpose, a process we haven't even started planning yet 😓 

I think we should change the title to `feat: ` and describe the functionality for the search bar, otherwise people might be encouraged to take this issue and then won't know how to resolve it 🍕

**Comment by SimranjitKaurMaan** [comment]
Sure @0-vortex , it completely makes sense to tag it as a feature. Renamed it.

**Comment by SimranjitKaurMaan** [comment]
opened feat: #789 cc: @0-vortex
