### ISSUE TITLE
Feature: Context clues needed in design system

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#804]
### Type of feature

🍕 Feature

### Current behavior

There are a few places in the app where users need to learn what they are looking at. At Netlify we used context cards to explain what features do on the page and link to the docs.

<img width="1548" alt="Screen Shot 2023-01-26 at 6 55 32 AM" src="https://user-images.githubusercontent.com/5713670/214868486-317eb91a-57bf-4d26-939a-69cce9f0da49.png">
<img width="1355" alt="Screen Shot 2023-01-26 at 6 55 23 AM" src="https://user-images.githubusercontent.com/5713670/214868555-54d737f3-5a10-4df2-aca0-f61c2d4b36a4.png">

### Suggested solution

Here are the locations we will need to design in some context clues

1. Dashboard. Users need context on why they are here and what they are looking at.
2. Contributors page. Not clear what to do there, and the connection to the filters
3. Reports. The context of This need on reports can be useful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by getaheaddev** [comment]
My suggestion is that we might not need context clues everywhere but that we could mix it with some text that would be on the page every time users visit the page. 

Before making the clues in the design we can see what adding text would be like and then we can determine how we would go about using actual context clues.

**Comment by 0-vortex** [comment]
> My suggestion is that we might not need context clues everywhere but that we could mix it with some text that would be on the page every time users visit the page.
> 
> Before making the clues in the design we can see what adding text would be like and then we can determine how we would go about using actual context clues.

Propose an incremental standardized approach to context cards UX:
- every type of content section that contains an `h1` or `h2` type of heading, should have a textual representation, summary, or generic "context clue" in order to account for the 15% logically relevant content for human beings and robots
- functional headings (h1 and h2) should not hide any content for any duration of time, especially if stored to server, as we are resetting sessions between builds thus completely invalidating that type of feature in favor of traditional tooltips or help dropdowns
- attaching comfortably designed context cards to key pieces of content (headings) with relevant content has a positive effect on the brain, making informational modals more readable in general even in non-heading areas, whereas temporary types of content (take action to display, have the functionality to hide, only read once, etc) increase the bias against executing the effort needed to digest that content

Really like the way netlify does this, and from a marketing/networking perspective, we need a lot more text for this analytical insights platform that everyone should be able to use to make more sense for both humans and robots; they will likely continue to be useful even in low growth scenario, while a pleasing design can provide incentive for veteran users not to request removing them 😅

**Comment by bdougie** [comment]
@getaheaddev can you confirm if this is ready for review?

**Comment by getaheaddev** [comment]
[[Context clue example](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?type=design&node-id=795-5072&t=lV7s8kPBlUJFbckr-4)]

**Comment by getaheaddev** [comment]
[[Highlights Feed](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?type=design&node-id=1043-5449&t=lV7s8kPBlUJFbckr-4)]
[[Insights Hub](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?type=design&node-id=627-4629&t=lV7s8kPBlUJFbckr-4)]

**Comment by getaheaddev** [comment]
@bdougie I feel like these are completed [[Design System: Context Clues](https://www.figma.com/file/jymWgr4kOgSpZYEoFrlgZQ/Design-System?type=design&node-id=1266-2327&t=BSQ0EN4E1Wtyb6Fx-4)]
