### ISSUE TITLE
Bug: users avatar is not showing on the repo tab

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/insights#832]
### Describe the bug

This is what it shows currently 
![Screenshot_20230203-010254](https://user-images.githubusercontent.com/72051159/216539888-2cdc1c6c-481d-43cc-aa74-1b3be6e75f9d.png)

### Steps to reproduce

1. Go to insights.opensauced.pizza
2. Click on the repository tab
3. See error 

### Affected services

insights.opensauced.pizza

### Platforms

Mobile

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
just also realized it the same on large screens
![image](https://user-images.githubusercontent.com/72051159/216540842-b2acfb9d-8177-4cba-b4be-a1163b023274.png)

**Comment by TAKANOME-DEV** [comment]
Yeah, I think it has something to do with cloudinary
![Screenshot from 2023-02-03 08-47-28](https://user-images.githubusercontent.com/79809121/216554179-804ebb57-1ca0-4f27-aa4d-0c070f65c450.png)
![Screenshot from 2023-02-03 08-47-45](https://user-images.githubusercontent.com/79809121/216554199-dd52de00-6f9a-47f5-90e9-4674f3b7a4c2.png)
cc @bdougie @OgDev-01 @brandonroberts @0-vortex

**Comment by 0-vortex** [comment]
@dev-phantom @TAKANOME-DEV this is an issue with cloudinary, cannot be solved other than removing the transformation and rounding the images from CSS 😅

**Comment by TAKANOME-DEV** [comment]
I think I know why :thinking: Give a second to try explaining it :sweat_smile:

**Comment by 0-vortex** [comment]
> @0-vortex a workaround is to change `isCached` props to `false` - if isCached is false, the GitHub link will be used `https://avatars.githubusercontent.com/u/6154722?v=4`
> 
> https://github.com/open-sauced/insights/blob/5bd4e48576d5f59b27d32eed4471f58c40a96082/components/molecules/TableRepositoryName/table-repository-name.tsx#L30-L36

You are correct about caching, but the issue is on a service level, not the way we request data - simply put, if we request more than 5000 non-cached avatars an hour that will rate limit the cloudinary service and the way it has been working so far is we just ignore it and request data every hour until we cache all our users (about 1200 active and 9000 repo owners).

Because the above limitation happens outside of our control, the image rounding comes with this compromise - the only way to completely disable this bug is to stop using the 3rd party service and request the avatars directly from github, thus benefitting from the increased rate limit of the authenticated user on the frontend purely in client (browser, non SSR) mode.

When we started using Cloudinary, our hourly users and displayed data was much less; we expect our active user data to increase 5-10x in resource consumption (that is the scaling of increasing active users displaying more data we make available).

The bug can definitely be fixed but requires additional steps like applying some CSS box rounding here and there after removing Cloudinary in the frontend! 🍕 🔥

**Comment by TAKANOME-DEV** [comment]
Well explained :clap: Thanks :pizza: 
Do you think a pr should be raised while waiting for the input of others?

**Comment by brandonroberts** [comment]
We would still have a potential issue if we have lots of traffic to public pages like the explore page. I think removing the usage of Cloudinary for the avatars for authenticated users is a good idea to offload the rate limiting. We switched to cached images before because we were running into the same issue pulling avatars directly from GitHub.

**Comment by bdougie** [comment]
> Do you think a pr should be raised while waiting for the input of others?

A PR would ideal. 5 days in and it is still broken.
