### ISSUE TITLE
Feature: rename the util function `getRelativeDays` to a clearer name

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#860]
### Type of feature

🧑‍💻 Refactor

### Current behavior

The function called `getRelativeDays` in `lib\utils\date-utils.ts` takes number of days and returns a formatted string that displays that number but in months or years like `10mo` or `1y`. The name of the function doesn't imply that this is what it actually does.

### Suggested solution

Rename it to be clearer & more informative on glance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by AhnafSulficar** [comment]
.take

**Comment by AhnafSulficar** [comment]
.take 
i hope ```getFormattedDuration``` is fine

**Comment by Deadreyo** [comment]
@bdougie @brandonroberts

**Comment by bdougie** [comment]
I'd say the current name works and pretty common to use relative in this context.

This is a phrase leveraged in the earliest js library that provides relative time for posting, Moment.js. 

The practice of relative time checking is common in social apps, and our implementation could be improved to show "2 days ago" instead of "April 28th, 2023"

**Comment by takanome-dev** [comment]
`getRelativeDays` is often used when calculating the pr velocity. We're currently using `formatDistanceToNowStrict` from `date-fns` to show "2 days ago" instead of something like "April 28th, 2023"

Are we going to update the name or close this issue @bdougie?
