### ISSUE TITLE
Tooling: update tooling setup to guard against some common use cases

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/insights#970]
### Type of feature

📦 Chore

### Current behavior

Tooling improvements to improve development and QOL

https://github.com/open-sauced/insights/pull/969#pullrequestreview-1329421094

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
What should we use for the tooling? eslint or prettier?
I know there was a discussion about this in https://github.com/open-sauced/insights/issues/386 but no decision was taken.

cc @0-vortex  @brandonroberts

**Comment by 0-vortex** [comment]
> What should we use for the tooling? eslint or prettier? I know there was a discussion about this in #386 but no decision was taken.
> 
> cc @0-vortex @brandonroberts

It was decided, we are using eslint across all repos. Reasons:
- prettier doesn't care about specifics
- eslint is superseding all formatting tools prettier offers
- we are running eslint with only auto-formattable rules, essentially emulating a better prettier experience without having any traces of it in the project

The specifics of this issue is related to our different configurations, for example the api exposing types and most of the data has this configuration: https://github.com/open-sauced/api.opensauced.pizza/blob/beta/.eslintrc.js while insights is using https://github.com/open-sauced/insights/blob/beta/.eslintrc.json

The backend rules are guarding against some of the mentioned quality of life improvements in the PR, however the refactor cost appears to be huge, with some rules incompatible to auto-fix between backend and frontend due to forced ignores and overrides. It should be noted tho, that the backend eslint configuration is based on the frontend one from the hot repo https://github.com/open-sauced/hot/blob/beta/.eslintrc.cjs however right now the most up to date one is in the public API 💯

**Comment by takanome-dev** [comment]
Thanks for the detailed explanation :+1: Can give it a shot if you don't mind

**Comment by brandonroberts** [comment]
I'd rather use prettier in frontend projects. eslint doesn't format correctly and folks are already using it on top of `npm run format`. So my proposal is to introduce a prettier config at minimum, and format files with prettier

**Comment by 0-vortex** [comment]
> I'd rather use prettier in frontend projects. eslint doesn't format correctly and folks are already using it on top of `npm run format`. So my proposal is to introduce a prettier config at minimum, and format files with prettier

https://dprint.dev ? :D

**Comment by takanome-dev** [comment]
Isn't this fixed by #1171 @brandonroberts?

**Comment by brandonroberts** [comment]
Yep, we can close this one.
