### ISSUE TITLE
Bug: close update dialog disables mouse event on page body

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#985]
### Describe the bug

https://user-images.githubusercontent.com/62995161/224093042-a718091e-2260-4133-9d35-352a86fc1328.mov

### Steps to reproduce

1. Connect account 
2. Go to user profile page
3. Click on more icon
4. select `Edit`
5. click on the `X` close icon

### Affected services

insights.opensauced.pizza

### Environment

Production, Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
This issue is caused by https://github.com/theKashey/react-remove-scroll-bar/issues/35#issuecomment-1276809669

The thing that I don't understand though is why the contributor highlight card is inside a radix dialog component and alert-dialog?
I'm having a lot of hydration issues and radix errors because `DialogTrigger` and `AlertDialogTrigger` are used outside of `Dialog/AlertDialog` wrapper :thinking:

I'm going to open a pr to fix the issues with dialogs not closing when clicking outside :v:

**Comment by Deadreyo** [comment]
The bug was fixed in #987 .

**Comment by TAKANOME-DEV** [comment]
> The bug was fixed in #987

Yeah, but the dialogs won't close when clicking outside

**Comment by Deadreyo** [comment]
> > The bug was fixed in #987
> 
> Yeah, but the dialogs won't close when clicking outside

Good idea but unrelated to this specific issue. Should open new issues for such ideas next time 😅.
